### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-common#660]
For https://github.com/phetsims/QA/issues/605. Done on Win 10 Chrome with CCK DC sim.
Start: 25.3
1 min: 111
2 min: 152
3 min: 192
4 min: 218
5 min: 242
6 min: 251
7 min: 227
8 min: console crashed.

I also noticed that, while fuzz testing for this memory test, sometimes the electrons would appear to be floating free of the objects. Not sure how to achieve this without fuzz testing.
<img width="381" alt="leftbehindmemtest" src="https://user-images.githubusercontent.com/41024075/107555317-401e6e00-6b94-11eb-9924-7c646cfc4d63.png">

**Comment by KatieWoe** [comment]
For comparison, here are the results from the published sim:
Start: 16.6
1 min: 33.8
2 min: 40.9
3 min: 68
4 min: 64.5
5 min: 39.4
6 min: 37.8
7 min: 56
8 min: 34.5
9 min: 32.8
10 min: 29

I also didn't notice the electron behavior from above

**Comment by samreid** [comment]
Thanks for finding this new problem, I corrected it on my side and ran a test over about 15 minutes:
![image](https://user-images.githubusercontent.com/679486/107840292-cb535b80-6d6e-11eb-815f-1a8158058cfd.png)

I'll commit shortly.

**Comment by samreid** [comment]
To try to make the tests more reproducible, I tried to press "Reset All" on both screens before capturing the memory snapshot--to try to avoid noise.  @KatieWoe can you please test on one platform in master?  If it seems good, please reassign to me and I'll cherry pick it into the RC.

**Comment by KatieWoe** [comment]
Here is my new memory test from master. It looks better:
<img width="417" alt="newmemtest" src="https://user-images.githubusercontent.com/41024075/107987868-0d0d1d80-6f8c-11eb-9e16-537976c7206a.png">
@samreid I did still see the odd electron behavior. Should this get it's own issue, or is it not worth an issue?
<img width="546" alt="electrons" src="https://user-images.githubusercontent.com/41024075/107987919-2a41ec00-6f8c-11eb-8d7a-402724f17fbf.png">

**Comment by samreid** [comment]
I opened a new issue for the electrons getting disassociated..

**Comment by samreid** [comment]
This is ready for spot checking in the deployments listed for https://github.com/phetsims/QA/issues/610, please close if it seems correct in RC.2.

**Comment by KatieWoe** [comment]
DC memory test:
<img width="413" alt="maybefixedmemtest" src="https://user-images.githubusercontent.com/41024075/108569971-17038900-72ca-11eb-8b43-36802e919377.png">
VL memory test:
<img width="415" alt="VLmemtest" src="https://user-images.githubusercontent.com/41024075/108569977-1d920080-72ca-11eb-922d-33e70f6512a3.png">
@samreid if these are expected numbers, please close.

**Comment by samreid** [comment]
That seems much better, thanks!  Closing.
